'use strict';
(async()=>{
const W=1024,H=1536,$=id=>document.getElementById(id),labels={neutral:'原表情',happy:'开心',shy:'害羞',surprised:'惊讶',angry:'生气',sad:'难过'},outfitLabels={original:'原装',overknee:'过膝白丝',tights:'白色裤袜'};
const state={expression:'neutral',outfit:'original',view:'full',background:'blue',paused:matchMedia('(prefers-reduced-motion: reduce)').matches,strength:.6,time:0,look:[0,0],target:[0,0],blinkAt:-100,nextBlink:2.2,nodAt:-100,lastCycle:0,recording:false};
let toastTimer,gl,program,textures=[],u={},numIndices=0,baseCanvas,closedCanvas,talkCanvas,talkClosedCanvas,images={},nextFrame,lastTs=0,uploadCount=0;
const toast=t=>{$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),2800);};
const create=()=>{const c=document.createElement('canvas');c.width=W;c.height=H;return c;};
const imageLoad=src=>new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>resolve(i);i.onerror=()=>reject(Error('有一张内置素材未能加载'));i.src=src;});
try{await Promise.all(Object.entries(ASSETS).map(async([k,v])=>{images[k]=await imageLoad(v);}));}catch(e){$('loading').textContent=e.message+'，请重新打开完整 HTML 文件。';return;}
for(const [id,label]of Object.entries(labels)){const b=document.createElement('button');b.className='expression';b.dataset.expression=id;b.setAttribute('aria-pressed',id==='neutral');b.setAttribute('aria-label',label);const i=document.createElement('img');i.src=ASSETS['thumb_'+id];i.alt='';b.append(i,document.createTextNode(label));b.onclick=()=>{selectExpression(id);$('cycle').checked=false;};$('expressionButtons').append(b);}
function selected(){document.querySelectorAll('button[data-expression]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.expression===state.expression));document.querySelectorAll('button[data-outfit]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.outfit===state.outfit));document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===state.view));document.querySelectorAll('[data-bg]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.bg===state.background));$('pause').textContent=state.paused?'继续动作':'暂停动作';$('stateBadge').textContent=state.paused?'已暂停':'动态预览';$('stateBadge').dataset.expression=state.expression;$('stateBadge').dataset.outfit=state.outfit;}
function selectExpression(id){state.expression=id;state.blinkAt=-100;compose();selected();}
function compose(){
 baseCanvas=create();const c=baseCanvas.getContext('2d');c.drawImage(images.original,0,0);if(state.outfit!=='original')c.drawImage(images['wardrobe_'+state.outfit],0,0);if(state.expression!=='neutral')c.drawImage(images['expr_'+state.expression],0,0);
 closedCanvas=create();let cc=closedCanvas.getContext('2d');cc.drawImage(baseCanvas,0,0);if(state.expression!=='happy'){cc.drawImage(images.blink_eye_left,0,0);cc.drawImage(images.blink_eye_right,0,0);}
 talkCanvas=create();let tc=talkCanvas.getContext('2d');tc.drawImage(baseCanvas,0,0);if(state.expression!=='happy'&&state.expression!=='surprised')tc.drawImage(images.surprised_mouth,0,0);
 talkClosedCanvas=create();let bc=talkClosedCanvas.getContext('2d');bc.drawImage(talkCanvas,0,0);if(state.expression!=='happy'){bc.drawImage(images.blink_eye_left,0,0);bc.drawImage(images.blink_eye_right,0,0);}
 if(gl){for(let i=0;i<4;i++){gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,textures[i]);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,[baseCanvas,closedCanvas,talkCanvas,talkClosedCanvas][i]);}uploadCount++;}
 else $('fallback').src=baseCanvas.toDataURL();
}
function initGL(){
 gl=$('stage').getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:false,preserveDrawingBuffer:true});if(!gl)return false;
 const vs=`attribute vec2 aPos;attribute vec2 aUV;varying vec2 vUV;uniform vec2 uSize;uniform vec2 uFocus;uniform float uZoom;uniform float uTime;uniform vec2 uLook;uniform vec4 uMotion;uniform float uNod;
 void main(){vec2 p=aPos;float y=p.y;float x=p.x;float amp=uMotion.w;float head=(1.-smoothstep(280.,420.,y))*smoothstep(290.,385.,x)*(1.-smoothstep(670.,740.,x));float lean=(1.-smoothstep(820.,1370.,y));float breathing=sin(uTime*1.85)*uMotion.x*amp;float a=(uLook.x*.038+sin(uTime*.72)*.008*amp*uMotion.x)*head;vec2 d=p-vec2(539.,300.);p=vec2(cos(a)*d.x-sin(a)*d.y,sin(a)*d.x+cos(a)*d.y)+vec2(539.,300.);p.x+=uLook.x*4.*head+uLook.x*2.*lean;p.y+=uLook.y*3.*head+uNod*8.*head-breathing*2.8*lean;p.x+=breathing*(x-530.)*.003*smoothstep(320.,470.,y)*(1.-smoothstep(750.,1000.,y));float hair=smoothstep(245.,550.,y)*(1.-smoothstep(935.,1060.,y))*max(1.-smoothstep(295.,450.,x),smoothstep(650.,805.,x));p.x+=(sin(uTime*1.6+y*.007+step(500.,x)*1.4)*6.+uLook.x*3.)*hair*uMotion.y*amp;p.y+=cos(uTime*1.1+x*.01)*1.8*hair*uMotion.y*amp;float skirt=smoothstep(530.,620.,y)*(1.-smoothstep(780.,865.,y))*smoothstep(310.,365.,x)*(1.-smoothstep(770.,850.,x));p.x+=sin(uTime*1.6+y*.018)*skirt*uMotion.y*amp;float fit=min(uSize.x/1024.,uSize.y/1536.)*.93*uZoom;vec2 q=(p-uFocus)*fit/uSize*2.;gl_Position=vec4(q.x,-q.y,0.,1.);vUV=aUV;}`;
 const fs=`precision mediump float;varying vec2 vUV;uniform sampler2D uTex0;uniform sampler2D uTex1;uniform sampler2D uTex2;uniform sampler2D uTex3;uniform float uBlink;uniform float uTalk;void main(){vec4 a=mix(texture2D(uTex0,vUV),texture2D(uTex1,vUV),uBlink);vec4 b=mix(texture2D(uTex2,vUV),texture2D(uTex3,vUV),uBlink);gl_FragColor=mix(a,b,uTalk);}`;
 function shader(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
 program=gl.createProgram();gl.attachShader(program,shader(gl.VERTEX_SHADER,vs));gl.attachShader(program,shader(gl.FRAGMENT_SHADER,fs));gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.useProgram(program);
 const cols=40,rows=60,verts=[],idx=[];for(let j=0;j<=rows;j++)for(let i=0;i<=cols;i++){verts.push(i*W/cols,j*H/rows,i/cols,j/rows);}for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){const a=j*(cols+1)+i,b=a+1,c=a+cols+1,d=c+1;idx.push(a,c,b,b,c,d);}
 const vb=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vb);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.STATIC_DRAW);for(const [name,offset]of [['aPos',0],['aUV',8]]){const l=gl.getAttribLocation(program,name);gl.enableVertexAttribArray(l);gl.vertexAttribPointer(l,2,gl.FLOAT,false,16,offset);}const ib=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,ib);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(idx),gl.STATIC_DRAW);numIndices=idx.length;
 for(const name of ['uSize','uFocus','uZoom','uTime','uLook','uMotion','uNod','uBlink','uTalk'])u[name]=gl.getUniformLocation(program,name);
 for(let i=0;i<4;i++){const t=gl.createTexture();textures.push(t);gl.activeTexture(gl.TEXTURE0+i);gl.bindTexture(gl.TEXTURE_2D,t);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.uniform1i(gl.getUniformLocation(program,'uTex'+i),i);}
 gl.clearColor(0,0,0,0);return true;
}
try{if(!initGL())throw Error('WebGL不可用');}catch(e){console.warn('动态渲染不可用，切换静态预览：',e.message);gl=null;$('stage').style.display='none';$('fallback').style.display='block';$('record').disabled=true;toast('此浏览器暂不支持动态渲染，表情切换和 PNG 导出仍然可用。');}
compose();selected();$('loading').hidden=true;
function render(ts){
 const dt=lastTs?Math.min((ts-lastTs)/1000,.05):0;lastTs=ts;if(!state.paused&&!document.hidden)state.time+=dt;const t=state.time;
 if(!state.paused){const follow=$('follow').checked;for(let i=0;i<2;i++)state.look[i]+=((follow?state.target[i]:0)-state.look[i])*Math.min(1,dt*5);if($('blink').checked&&t>state.nextBlink){state.blinkAt=t;state.nextBlink=t+3.1+Math.random()*2.3;}if($('cycle').checked&&t-state.lastCycle>3.4){const keys=Object.keys(labels);selectExpression(keys[(keys.indexOf(state.expression)+1)%keys.length]);state.lastCycle=t;}}
 const age=t-state.blinkAt;let blink=age<0||age>.22?0:age<.07?age/.07:age<.13?1:(.22-age)/.09;if(state.expression==='happy')blink=0;const nodAge=t-state.nodAt;const nod=nodAge>=0&&nodAge<1.1?Math.sin(nodAge/1.1*Math.PI*2)*Math.sin(nodAge/1.1*Math.PI):0;let talk=$('talk').checked?Math.max(0,Math.sin(t*14))*.85:0;
 if(gl){const c=$('stage'),rect=c.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);const width=Math.round(rect.width*dpr),height=Math.round(rect.height*dpr);if(c.width!==width||c.height!==height){c.width=width;c.height=height;gl.viewport(0,0,width,height);}const views={full:[512,768,1],bust:[526,398,1.9],face:[546,209,4.5]},v=views[state.view];gl.uniform2f(u.uSize,width,height);gl.uniform2f(u.uFocus,v[0],v[1]);gl.uniform1f(u.uZoom,v[2]);gl.uniform1f(u.uTime,t);gl.uniform2f(u.uLook,state.look[0]*state.strength,state.look[1]*state.strength);gl.uniform4f(u.uMotion,$('breathe').checked?1:0,$('hair').checked?1:0,0,state.strength);gl.uniform1f(u.uNod,nod*state.strength);gl.uniform1f(u.uBlink,blink);gl.uniform1f(u.uTalk,talk);gl.clear(gl.COLOR_BUFFER_BIT);gl.drawElements(gl.TRIANGLES,numIndices,gl.UNSIGNED_SHORT,0);}
 $('stage').dataset.motionTime=t.toFixed(2);$('stage').dataset.blink=blink.toFixed(2);$('stage').dataset.look=state.look.map(x=>x.toFixed(2)).join(',');nextFrame=requestAnimationFrame(render);
}
nextFrame=requestAnimationFrame(render);
document.querySelectorAll('button[data-outfit]').forEach(b=>b.onclick=()=>{state.outfit=b.dataset.outfit;compose();selected();});
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;selected();});
document.querySelectorAll('[data-bg]').forEach(b=>b.onclick=()=>{state.background=b.dataset.bg;$('stageBg').className='stage-bg '+(state.background==='blue'?'':state.background);$('stageCard').classList.toggle('dark-mode',state.background==='dark');selected();});
$('strength').oninput=()=>{state.strength=Number($('strength').value)/100;$('strengthValue').value=$('strength').value+'%';};
$('pause').onclick=()=>{state.paused=!state.paused;selected();};
$('wink').onclick=()=>{state.paused=false;state.blinkAt=state.time;selected();};
$('stage').addEventListener('pointermove',e=>{const r=e.currentTarget.getBoundingClientRect();state.target=[Math.max(-1,Math.min(1,(e.clientX-r.left)/r.width*2-1)),Math.max(-1,Math.min(1,(e.clientY-r.top)/r.height*2-1))];});
$('stage').addEventListener('pointerleave',()=>{state.target=[0,0];});$('stage').addEventListener('click',()=>{state.paused=false;state.nodAt=state.time;selected();});
document.addEventListener('visibilitychange',()=>{lastTs=0;});
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
$('export').onclick=()=>{baseCanvas.toBlob(b=>{if(!b){toast('图片导出失败，请重试。');return;}download(b,'角色_'+labels[state.expression]+'_'+outfitLabels[state.outfit]+'.png');toast('已导出透明背景的 1024 × 1536 PNG');},'image/png');};
$('record').onclick=()=>{
 if(state.recording||!gl)return;if(!window.MediaRecorder||!HTMLCanvasElement.prototype.captureStream){toast('当前浏览器不支持录制，请使用新版 Chrome 或 Edge。');return;}
 const mime=['video/webm;codecs=vp9','video/webm;codecs=vp8','video/webm','video/mp4'].find(s=>MediaRecorder.isTypeSupported(s));if(!mime){toast('当前浏览器没有可用的视频编码器。');return;}
 const c=document.createElement('canvas');c.width=768;c.height=1152;const ctx=c.getContext('2d');const stream=c.captureStream(30);let rec;try{rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:4500000});}catch(e){stream.getTracks().forEach(x=>x.stop());toast('无法启动录制：'+e.message);return;}
 state.recording=true;state.paused=false;selected();$('record').disabled=true;const chunks=[];let recordingRAF,start=performance.now();
 function draw(now){ctx.fillStyle=state.background==='dark'?'#293951':state.background==='cream'?'#fff1e5':'#edf3ff';ctx.fillRect(0,0,c.width,c.height);const s=$('stage'),scale=Math.min(c.width/s.width,c.height/s.height);ctx.drawImage(s,(c.width-s.width*scale)/2,(c.height-s.height*scale)/2,s.width*scale,s.height*scale);$('record').textContent='录制中 '+Math.max(0,Math.ceil(6-(now-start)/1000))+' 秒';recordingRAF=requestAnimationFrame(draw);}recordingRAF=requestAnimationFrame(draw);
 rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};const cleanup=()=>{cancelAnimationFrame(recordingRAF);stream.getTracks().forEach(x=>x.stop());state.recording=false;$('record').disabled=false;$('record').textContent='录制 6 秒动画';};rec.onerror=()=>{cleanup();toast('录制失败，请重新打开文件再试。');};rec.onstop=()=>{cleanup();if(chunks.length){download(new Blob(chunks,{type:mime}),'角色动态_'+labels[state.expression]+(mime.includes('mp4')?'.mp4':'.webm'));toast('6 秒动画已导出');}else toast('录制没有得到画面，请保持页面在前台后重试。');};rec.start();setTimeout(()=>{if(rec.state==='recording')rec.stop();},6000);
};
$('reset').onclick=()=>{state.expression='neutral';state.outfit='original';state.view='full';state.background='blue';state.strength=.6;state.paused=false;state.target=[0,0];state.blinkAt=-100;for(const id of ['blink','breathe','hair','follow'])$(id).checked=true;for(const id of ['talk','cycle'])$(id).checked=false;$('strength').value=60;$('strengthValue').value='60%';$('stageBg').className='stage-bg';$('stageCard').classList.remove('dark-mode');compose();selected();toast('已恢复默认设置');};
window.addEventListener('keydown',e=>{if(/INPUT|BUTTON/.test(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();$('pause').click();}if(/^[1-6]$/.test(e.key))selectExpression(Object.keys(labels)[Number(e.key)-1]);});
})();
